[package]
name = "client-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axum = "0.8.1"
axum-cookie = "0.1.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
