services:
  proxy:
    container_name: pingpath-proxy-dev
    build:
      context: .
      dockerfile: docker/Dockerfile.proxy.dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/app
      - ./docker/Caddyfile.dev:/etc/Caddyfile
      - ./data/caddy:/data/caddy

  api:
    container_name: pingpath-api-dev
    build:
      context: .
      dockerfile: docker/Dockerfile.api.dev
    volumes:
      - ./backend:/app
