FROM node:lts-alpine AS runtime
WORKDIR /app

RUN apk add --no-cache caddy
RUN npm install -g concurrently

ENTRYPOINT ["npx", "concurrently", \
    "\"cd frontend && npm i && npx vite --port 8080\"", \
    "\"caddy run --config docker/Caddyfile.dev --adapter caddyfile --watch\""]

