FROM node:lts-alpine AS runtime
WORKDIR /app

RUN apk add --no-cache caddy
RUN npm install -g concurrently

ENTRYPOINT ["npx", "concurrently", \
    "\"npm i && npx vite --port 8080\"", \
    "\"caddy run --config /etc/Caddyfile --adapter caddyfile --watch\""]

